SistemaFirma/app/FirmaSeduzac/FirmaSeduzac/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio/', include('FirmaCertificadosApp.urls')),
    path('', include('Login.urls')),
    path('certificados_completos/', include('CertificacionesCompletasApp.urls')),
    path('certificados_parciales/', include('CertificacionesParcialesApp.urls')),
    path('bachillerato_distancia/', include('BachilleratoDistanciaApp.urls')),
    path('por_escuela/', include('PorEscuelaApp.urls')),
    path('configuracion/', include('ConfiguracionApp.urls')),
    path('firmar/', include('FirmarApp.urls')),
    path('certificados_historicos/', include('HistoricasApp.urls')),
    path('cancelar_certificados/', include('CancelarCertApp.urls'))
]

handler403 = 'ConfiguracionApp.views.error_403'

SistemaFirma/app/FirmaSeduzac/HistoricasApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.certificaciones_historicas, name="certificaciones_historicas"),
]

SistemaFirma/app/FirmaSeduzac/Login/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, LoginView

urlpatterns = [
    path('',views.LoginView.as_view(), name="login"),
    path('logout/',LogoutView.as_view(), name="logout"),
    path('register/', views.RegisterView.as_view(), name='register'),

]

SistemaFirma/app/FirmaSeduzac/HistoricasApp/forms.py
from django import forms

# Formulario para la CURP a verificaar
class CertificacionHForm(forms.Form):
    curp = forms.CharField(
        label='CURP',
        max_length=18,
        widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 300px'})
    )

SistemaFirma/app/FirmaSeduzac/HistoricasApp/views.py
from django.shortcuts import render, redirect
from .forms import CertificacionHForm
from django.db import connection, connections
from ConfiguracionApp.models import FolioLetra, FolioSequence
from .utils import *
from FirmaSeduzac.settings import LETRA_FOLIO_TB, LETRA_FOLIO_BACHILLERATO_DISTANCIA

# fecha_cert
def get_fecha_certificado(cursor,curp):
    query = "SELECT fecha_cert FROM alumno_cert_historia WHERE curp = %s"

    cursor.execute(query,[curp])
    fecha_cert = cursor.fetchone()
    if(fecha_cert):
        fecha = fecha_cert[0]
    else:
        fecha = None

    return fecha

#fecha_certificado
def get_fecha_certificacion(cursor, curp):
    query = "SELECT fecha_certificacion FROM alumno_cert_historia WHERE curp = %s"

    cursor.execute(query,[curp])
    fecha_cert = cursor.fetchone()
    if(fecha_cert):
        fecha = fecha_cert[0]
    else:
        fecha = None

    return fecha

def buscar_certificado(cursor,curp, fecha_cert, fecha_certificacion):
    if(fecha_cert == None):
        query_fecha_cert = ("UPDATE alumno_cert_historia SET fecha_cert = %s WHERE curp = %s")
        cursor.execute(query_fecha_cert,[fecha_certificacion,curp])
    else:
        query_fecha_cert = ("UPDATE alumno_cert_historia SET fecha_certificacion = %s WHERE curp = %s")
        cursor.execute(query_fecha_cert,[fecha_cert,curp])
    query = ("SELECT id_hist_estudio, curp, estatus_certificado, folio_sep, nombre_ct, clavecct, prim_apellido, seg_apellido, nombre, "
            "promedio, fecha_cert, observaciones_tec, sello_seduzac, fecha_certificacion, bachillerato, autoridad_educativa, "
            "certificado_autoridad_educativa FROM alumno_cert_historia WHERE curp = %s")
    cursor.execute(query, [curp])
    result = cursor.fetchone()
    if(result):
        return dict(zip(['id_hist_estudio', 'curp', 'estatus_certificado', 'folio_sep', 'nombre_ct', 'clavecct', 
                         'prim_apellido', 'seg_apellido', 'nombre', 'promedio', 
                         'fecha_cert', 'observaciones_tec', 'sello_seduzac', 
                         'fecha_certificacion', 'bachillerato', 
                         'autoridad_educativa', 'certificado_autoridad_educativa'], result))
    else:
        return None
    
def obtener_estatus_certificado(cursor, curp):
    query = "SELECT estatus_certificado FROM alumno_cert_historia WHERE curp = %s"
    cursor.execute(query, [curp])

    estatus = cursor.fetchone()
    if(estatus):
        estatus_certificado = estatus[0]
    else:
        estatus_certificado = None
    return estatus_certificado


def obtener_valores_cadena(cursor, curp):
    rfc = "SAFC7105149R3"
    documento = "certificado"
    sistema = "certificacion"
    cadena = ""

    query = (
        "SELECT curp, nombre, prim_apellido, seg_apellido, promedio, clavecct FROM alumno_cert_historia "
        "WHERE curp = %s"
    )

    cursor.execute(query, [curp])
    alumno = cursor.fetchone()

    if(alumno):
        curp_alumno = alumno[0]
        nombre = alumno[1]
        ap_paterno = alumno[2]
        ap_materno = alumno[3]
        promedio = alumno[4]
        clavecct = alumno[5]
        fecha = datetime.now()
        fecha_final = fecha.strftime('%Y-%m-%d %H:%M:%S')

    print(alumno)

    cadena = f"||1.0|3|SAFC710514MDFLLR06|Secretaria de Educación|SECRETARÍA DE EDUCACIÓN DEL ESTADO DE ZACATECAS|Secretaría de Educación del Estado de Zacatecas|{clavecct}|000|32|{curp_alumno}|{nombre}|{ap_paterno}|{ap_materno}|3|{promedio}|{fecha_final}||"
    # print(cadena)
    firma = api_firma(rfc, documento, sistema, cadena)
    respuesta_json = json.loads(firma)
    sello = respuesta_json["sello"]
    uuid = respuesta_json["uuid"]
    fecha_firma = respuesta_json["fecha"]
    # print(f'SELLO : {sello}')
    # print(f'UUID : {uuid}')
    # print(f'FECHA : {fecha_firma}')

    valores_cadena = {'sello':sello, 'uuid':uuid, 'fecha':fecha_firma}

    return valores_cadena

def fecha_cert_texto(valores_cadena):
    fecha_texto = valores_cadena['fecha']
    fecha_res = fecha_a_texto(fecha_texto)

    return fecha_res

def firmar_certificado(cursor, curp, valores_cadena):
    id_proceso = 11111
    certificado_digital = ""
    estatus = 1
    fecha_firma = valores_cadena['fecha']
    fecha_texto = fecha_cert_texto(valores_cadena)
    sello = valores_cadena['sello']

    query = (
        "UPDATE alumno_cert_historia SET id_proceso = %s, certificado_digital = %s, estatus_certificado = %s, "
        "fecha_firma = %s, fecha_cert_texto = %s, sello_seduzac = %s WHERE curp = %s"
    )
    cursor.execute(query, [id_proceso, certificado_digital, estatus, fecha_firma, fecha_texto, sello, curp])

def obtener_clave_cct(cursor,curp):
    query = (
        "SELECT ac.clavecct FROM alumno_cert_historia ac WHERE ac.curp = %s"
    )
    cursor.execute(query,[curp])
    clavecct = cursor.fetchone()
    clavecct = clavecct[0]
    
    # print(f'LETRA: {LETRA_FOLIO}')
    return clavecct

def obtener_nombre_ct(cursor, curp):
    query = ("SELECT nombre_ct FROM alumno_cert_historia WHERE curp = %s;")

    cursor.execute(query,[curp])
    nombre_ct = cursor.fetchone()
    nombre_ct = nombre_ct[0]
    
    return nombre_ct

def foliar_certificado_prepas(cursor, clavecct, curp, nombre_ct):
    try:
        foliador_prepa = FolioLetra.objects.latest('id')
    except:
        foliador_prepa = 'A'

    clave = clavecct[2:5]
    foliador = None
    if((clave == 'EBH' or clave == 'PBH') and nombre_ct != 'BACHILLERATO A DISTANCIA'):
        foliador = foliador_prepa
    elif(clave == 'ETK'):
        foliador = LETRA_FOLIO_TB
    elif(clave == 'EBH' and nombre_ct == 'BACHILLERATO A DISTANCIA'):
        foliador = LETRA_FOLIO_BACHILLERATO_DISTANCIA

    folio_sequence = FolioSequence.objects.create()
    folio_id = folio_sequence.id

    folio = f'{foliador}{str(folio_id).zfill(4)}'

    query = (
        "UPDATE alumno_cert_historia SET folio_sep = %s WHERE curp = %s"
    )

    cursor.execute(query,[folio,curp])

def certificaciones_historicas(request):
    form = CertificacionHForm(request.POST or None)
    alumno_info = None
    error = None
    boton_firmar = None
    seccion_datos = None
    fecha_cert = None
    fecha_certificacion = None
    mensaje_firma = None
    error_clave = None
    mensaje_firmado = None
    mensaje_no_firmado = None

    if (request.method == "POST"):
        with connections['mariadb'].cursor() as cursor:
            if(form.is_valid()):
                curp = form.cleaned_data['curp'].upper()
                request.session['curp'] = curp #Aqui guardo la curp en la sesion
                fecha_cert = get_fecha_certificado(cursor, curp)
                fecha_certificacion = get_fecha_certificacion(cursor,curp)
                alumno_info = buscar_certificado(cursor, curp, fecha_cert, fecha_certificacion)
                estatus = obtener_estatus_certificado(cursor,curp)

                if (not alumno_info):
                    error = "Este alumno no cuenta con certificado"
                    seccion_datos = True
                    boton_firmar = False
                else:
                    if(estatus in (103,1,2,4)):
                        boton_firmar = False
                        mensaje_firmado = "Este alumno ya cuenta con un certificado firmado."
                    else:
                        boton_firmar = True
                        mensaje_no_firmado = "Este alumno aún no cuenta con certificado firmado. Presione el botón de 'Firmar' si desea firmar el certificado."
                        if('firmar' in request.POST):
                            clave = obtener_clave_cct(cursor, curp)
                            if(clave == " " or clave is None or clave == ""):
                                error_clave = "El alumno no cuenta con clave de centro de trabajo. Verifique los datos."
                            else:
                                valores_cadena = obtener_valores_cadena(cursor, curp)
                                nombre_ct = obtener_nombre_ct(cursor, curp)
                                firmar_certificado(cursor, curp, valores_cadena)
                                mensaje_firma = "Se firmó correctamente el certificado."
                                boton_firmar = False
                                foliar_certificado_prepas(cursor, clave, curp, nombre_ct)
                                alumno_info = buscar_certificado(cursor, curp, fecha_cert, fecha_certificacion)
    return render(request,"cert_hist.html",{'form':form,
                                            'alumno_info':alumno_info,
                                            'error':error,
                                            'boton_firmar':boton_firmar,
                                            'seccion_datos':seccion_datos,
                                            'mensaje_firma':mensaje_firma,
                                            'error_clave':error_clave,
                                            'mensaje_firmado':mensaje_firmado,
                                            'mensaje_no_firmado':mensaje_no_firmado})

SistemaFirma/app/FirmaSeduzac/HistoricasApp/templates/buscar_certificado_hist.html
<section style="border: 1px solid #ccc; padding: 10px; background-color: #f9f9f9; margin-bottom: 20px;">
    <h3>Verificar Certificado</h3>
    <form method="post" style="width: 100%;">
        {% csrf_token %}
        <div style="display: flex; align-items: center;">
            <div>
                <label for="id_curp">CURP del Alumno:</label>
                {{ form.curp }}
            </div>
            <button type="submit" class="btn btn-success" style="margin-left: 10px; margin-top: 30px">Enviar</button>
        </div>
    {% if alumno_info %}
        <h3>Certificado</h3>
        <div style="overflow-x: auto;">
            <table class="table">
                <tr>
                    <th>CURP</th>
                    <th>Estatus Certificado</th>
                    <th>Folio SEP</th>
                    <th>Nombre CT</th>
                    <th>Clave CT</th>
                    <th>Primer Apellido</th>
                    <th>Segundo Apellido</th>
                    <th>Nombre</th>
                    <th>Promedio</th>
                    <th>Fecha de Certificado</th>
                    <th>Observaciones</th>
                    <th style="text-align:center">Sello SEDUZAC</th>
                    <th>Fecha Certificación</th>
                    <th>Bachillerato</th>
                    <th>Autoridad Educativa</th>
                    <th>Certificado Autoridad Educativa</th>
                </tr>
                <tr>
                    <td>{{ alumno_info.curp }}</td>
                    {% if alumno_info.estatus_certificado == 1 %}
                        <td>Firmado</td>
                    {% elif alumno_info.estatus_certificado == 0 %}
                        <td>Por Firmar</td>
                    {% elif alumno_info.estatus_certificado == 2 %}
                        <td>Firmado SEP</td>
                    {% elif alumno_info.estatus_certificado == 3 %}
                        <td>Cancelado</td>
                    {% elif alumno_info.estatus_certificado == 4 %}
                        <td>Impreso</td>
                    {% elif alumno_info.estatus_certificado == 5 %}
                        <td>Para Cancelar</td>
                    {% elif alumno_info.estatus_certificado == 103 %}
                        <td>Validada</td>
                    {% elif alumno_info.estatus_certificado == 100 %}
                        <td>Inicial Feria de Servicios</td>
                    {% elif alumno_info.estatus_certificado == 101 %}
                        <td>Procesando</td>
                    {% elif alumno_info.estatus_certificado == 102 %}
                        <td>No se encontró información</td>
                    {% endif %}
                    {% if alumno_info.folio_sep %}
                        <td>{{ alumno_info.folio_sep }}</td>
                    {% else %}
                        <td>Sin Folio</td>
                        {% endif %}
                    <td>{{ alumno_info.nombre_ct }}</td>
                    <td>{{ alumno_info.clavecct }}</td>
                    <td>{{ alumno_info.prim_apellido }}</td>
                    <td>{{ alumno_info.seg_apellido }}</td>
                    <td>{{ alumno_info.nombre }}</td>
                    {% if alumno_info.promedio %}
                    <td>{{ alumno_info.promedio }}</td>
                    {% else %}
                    <td>Sin Promedio</td>
                    {% endif %}
                    <td>{{ alumno_info.fecha_cert }}</td>
                    {% if alumno_info.observaciones_tec %}
                    <td>{{ alumno_info.observaciones_tec }}</td>
                    {% else %}
                    <td>Sin observaciones</td>
                    {% endif %}
                    {% if alumno_info.sello_seduzac %}
                        <td style="white-space: nowrap; max-width: 200px; overflow: hidden; text-overflow: ellipsis;">
                            <div style="overflow-x: auto; white-space: nowrap;">
                                {{ alumno_info.sello_seduzac }}
                            </div>
                        </td>
                    {% else %}
                        <td>Sin Sello</td>
                    {% endif %}
                    {% if alumno_info.fecha_certificacion %}
                    <td>{{ alumno_info.fecha_certificacion }}</td>
                    {% else %}
                    <td>Sin fecha</td>
                    {% endif %}
                    {% if alumno_info.bachillerato %}
                    <td>{{ alumno_info.bachillerato }}</td>
                    {% else %}
                    <td>Sin Bachillerato</td>
                    {% endif %}
                    <td style="white-space: nowrap; max-width: 200px; overflow: hidden; text-overflow: ellipsis;">
                        <div style="overflow-x: auto; white-space: nowrap;">
                            {{ alumno_info.autoridad_educativa }}
                        </div>
                    </td>
                    <td>{{ alumno_info.certificado_autoridad_educativa }}</td>
                </tr>
            </table>
        </div>
        {% if boton_firmar %}
        <button type="submit" name="firmar" value="firmar" class="btn btn-success" style="margin-top: 30px;">
            Firmar
        </button>
        {% endif %}
    </form>
    {% elif error %}
        <p class="alert alert-warning" style="width:25%; margin-top:10px">{{ error }}</p>
    {% endif %}
    {% if mensaje_firma %}
        <p class="alert alert-success" style="width:25%; margin-top:10px">{{ mensaje_firma }}</p>
    {% endif %}
    {% if error_clave %}
        <p class="alert alert-danger" style="width:25%; margin-top:10px">{{ error_clave }}</p>
    {% endif %}
    {% if mensaje_firmado %}
        <p class="alert alert-success" style="width:25%; margin-top:10px">{{ mensaje_firmado }}</p>
    {% endif %}
    {% if mensaje_no_firmado %}
        <p class="alert alert-warning" style="width:25%; margin-top:10px">{{ mensaje_no_firmado }}</p>
    {% endif %}
</section>

SistemaFirma/app/FirmaSeduzac/HistoricasApp/templates/cert_hist.html
{% extends "base2.html" %}

{% block titulo %}
    Certificaciones Historicas
{% endblock titulo %}

{% block content %}
<body>
    <section style="border: 5px solid #ccc; padding: 10px; background-color: #DCDCDC; margin-bottom: 20px; text-align:center;">
    <h2>Certificaciones Históricas(Feria)</h2>
    </section>
    <!-- Sección para verificar el certificado -->
    {% include "buscar_certificado_hist.html" %}

</body>
</html>
{% endblock %}

SistemaFirma/app/FirmaSeduzac/HistoricasApp/templates/datos_alumnoCH.html
<section style="border: 1px solid #ccc; padding: 10px; background-color: #f9f9f9; margin-bottom: 20px;">
    <h3>Datos del Alumno</h3>
    {% if datos_alumno %}
    <div style="overflow-x: auto;">
        <table class="table">
            <tr>
                <th>CURP</th>
                <th>Apellido Paterno</th>
                <th>Apellido Materno</th>
                <th>Nombre</th>
                <th style="text-align:center;">Estatus del Alumno</th>
            </tr>
            <tr>
                <td>{{ datos_alumno.curp }}</td>
                <td>{{ datos_alumno.app_alumno }}</td>
                <td>{{ datos_alumno.apm_alumno }}</td>
                <td>{{ datos_alumno.nom_alumno }}</td>
                {% if datos_alumno.alumno_estatus == "I" %}
                <td style="text-align:center;">TERMINADO CON CERTIFICADO IMPRESO</td>
                {% elif datos_alumno.alumno_estatus == "N" %}
                <td style="text-align:center;">NUEVO / ALTA</td>
                {% elif datos_alumno.alumno_estatus == "B" %}
                <td style="text-align:center;">BAJA TEMPORAL</td>
                {% elif datos_alumno.alumno_estatus == "D" %}
                <td style="text-align:center;">BAJA DEFINITIVA</td>
                {% elif datos_alumno.alumno_estatus == "R" %}
                <td style="text-align:center;">PROMOVIDO IRREGULAR</td>
                {% elif datos_alumno.alumno_estatus == "P" %}
                <td style="text-align:center;">PROMOVIDO</td>
                {% elif datos_alumno.alumno_estatus == "X" %}
                <td style="text-align:center;">ERRONEO</td>
                {% elif datos_alumno.alumno_estatus == "V" %}
                <td style="text-align:center;">VERIFICADO</td>
                {% elif datos_alumno.alumno_estatus == "W" %}
                <td style="text-align:center;">REGISTRO ELIMINADO</td>
                {% endif %}
            </tr>
        </table>
    </div>
    {% elif error_clave %}
    <p class="alert alert-warning" style="width:25%; margin-top:10px">{{ error_clave }}</p>
    {% endif %}
</section>